package intelligence

import (
	"fmt"
	"strings"
	"time"

	d "toollab-core/internal/pipeline/usecases/domain"
)

// Generate builds the full EndpointIntelligence artifact from a dossier.
func Generate(dossier *d.DossierV2Full) *d.EndpointIntelligence {
	baseURL := dossier.TargetProfile.BaseURL
	now := time.Now().UTC()
	runMode := dossier.RunMode

	evidenceByEP := indexEvidenceByEndpoint(dossier.Runtime.EvidenceSamples)
	contractByEP := indexContractsByEndpoint(dossier.Runtime.InferredContracts)
	annotByEP := indexAnnotationsByEndpoint(dossier.Runtime.SemanticAnnotations)
	authByEP := indexAuthByEndpoint(dossier.Runtime.AuthMatrix)
	smokeByEP := indexSmokeByEndpoint(dossier.Runtime.SmokeResults)
	findingsByEP := indexFindingsByEndpoint(dossier.FindingsRaw)
	patternsByEP := indexPatternsByEndpoint(dossier.AST.ASTCodePatterns, dossier.AST.EndpointCatalog.Endpoints)

	domainMap := make(map[string]*d.IntelDomain)
	var domainOrder []string

	for _, ep := range dossier.AST.EndpointCatalog.Endpoints {
		domName, domBasis := classifyDomain(ep, &dossier.AST.RouterGraph, dossier.AST.ASTEntities)

		dom, exists := domainMap[domName]
		if !exists {
			dom = &d.IntelDomain{
				DomainName:  domName,
				DomainBasis: domBasis,
			}
			domainMap[domName] = dom
			domainOrder = append(domainOrder, domName)
		}

		evidence := evidenceByEP[ep.EndpointID]
		contract := contractByEP[ep.EndpointID]
		annot := annotByEP[ep.EndpointID]
		authEntry := authByEP[ep.EndpointID]
		smoke := smokeByEP[ep.EndpointID]
		findings := findingsByEP[ep.EndpointID]
		patterns := patternsByEP[ep.EndpointID]

		intel := buildEndpointIntel(ep, baseURL, evidence, contract, annot, authEntry, smoke, findings, patterns, &dossier.TargetProfile, runMode)

		dom.Endpoints = append(dom.Endpoints, intel)
	}

	if runMode == d.RunModeOffline {
		for _, dom := range domainMap {
			dom.DomainDescription = "SERVICE OFFLINE. " + buildDomainDescription(dom) +
				" No runtime evidence was collected. Use the Try It playground to test connectivity."
		}
	} else {
		for _, dom := range domainMap {
			dom.DomainDescription = buildDomainDescription(dom)
		}
	}

	var domains []d.IntelDomain
	for _, name := range domainOrder {
		domains = append(domains, *domainMap[name])
	}

	openQuestions := buildOpenQuestions(dossier)

	return &d.EndpointIntelligence{
		SchemaVersion: "v1",
		RunID:         dossier.RunID,
		BaseURL:       baseURL,
		GeneratedAt:   now,
		Domains:       domains,
		OpenQuestions: openQuestions,
	}
}

// GenerateIndex builds a lightweight index for the frontend table.
func GenerateIndex(intel *d.EndpointIntelligence) *d.IntelIndex {
	idx := &d.IntelIndex{
		SchemaVersion: "v1",
		RunID:         intel.RunID,
		BaseURL:       intel.BaseURL,
	}

	for _, dom := range intel.Domains {
		idx.Domains = append(idx.Domains, d.IntelDomainSummary{
			DomainName:    dom.DomainName,
			EndpointCount: len(dom.Endpoints),
		})
		for _, ep := range dom.Endpoints {
			idx.Endpoints = append(idx.Endpoints, d.IntelEndpointIndex{
				EndpointID:   ep.EndpointID,
				Method:       ep.Method,
				Path:         ep.PathTemplate,
				OperationID:  ep.OperationID,
				Domain:       dom.DomainName,
				AuthRequired: ep.Auth.Required,
				Summary:      ep.WhatItDoes.Summary,
				Confidence:   ep.WhatItDoes.Confidence,
				CommandCount: len(ep.HowToQuery.ReadyCommands),
				HasEvidence:  len(ep.EvidenceRefs) > 0,
			})
			idx.TotalEndpoints++
		}
	}

	return idx
}

// GenerateQueryScripts builds all shell scripts as a single artifact.
func GenerateQueryScripts(intel *d.EndpointIntelligence) *d.EndpointQueryScripts {
	scripts := &d.EndpointQueryScripts{
		SchemaVersion: "v1",
		RunID:         intel.RunID,
		BaseURL:       intel.BaseURL,
		Scripts:       make(map[string]d.EndpointScriptSet),
	}

	for _, dom := range intel.Domains {
		for _, ep := range dom.Endpoints {
			set := d.EndpointScriptSet{}
			header := fmt.Sprintf("#!/bin/bash\n# Endpoint: %s %s\n# Generated by ToolLab v2\n\nBASE_URL=\"%s\"\nTOKEN=\"${TOKEN:-}\"\n\n",
				ep.Method, ep.PathTemplate, intel.BaseURL)

			for _, cmd := range ep.HowToQuery.ReadyCommands {
				script := header + "# " + cmd.Name + "\n" + cmd.Command + "\n"
				switch cmd.Name {
				case "curl_happy_path":
					set.HappyPath = script
				case "curl_no_auth":
					set.NoAuth = script
				case "curl_invalid_auth":
					set.InvalidAuth = script
				}
			}

			if len(ep.HowToQuery.QueryVariants) > 0 {
				var variantScript strings.Builder
				variantScript.WriteString(header)
				for _, v := range ep.HowToQuery.QueryVariants {
					variantScript.WriteString(fmt.Sprintf("# %s: %s\n%s\n\n", v.VariantName, v.Description, v.Command))
				}
				set.Variants = variantScript.String()
			}

			set.HTTPFile = buildHTTPFile(ep, intel.BaseURL)

			scripts.Scripts[ep.EndpointID] = set
		}
	}

	return scripts
}

func buildHTTPFile(ep d.IntelEndpoint, baseURL string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("### %s %s\n", ep.Method, ep.PathTemplate))
	sb.WriteString(fmt.Sprintf("# %s\n\n", ep.WhatItDoes.Summary))

	url := strings.TrimRight(baseURL, "/") + ep.PathTemplate
	sb.WriteString(fmt.Sprintf("%s %s HTTP/1.1\n", ep.Method, url))

	if ep.Auth.Required == "yes" || ep.Auth.Required == "unknown" {
		if ep.Auth.Mechanism == "api_key" {
			sb.WriteString(fmt.Sprintf("X-API-Key: {{api_key}}\n"))
		} else {
			sb.WriteString("Authorization: Bearer {{token}}\n")
		}
	}

	if isBodyMethod(ep.Method) {
		sb.WriteString("Content-Type: application/json\n")
		sb.WriteString("\n{}\n")
	}

	sb.WriteString("\n")
	return sb.String()
}

func buildEndpointIntel(
	ep d.EndpointEntry,
	baseURL string,
	evidence []d.EvidenceSample,
	contract *d.InferredContract,
	annot *d.SemanticAnnotation,
	authEntry *d.AuthMatrixEntry,
	smoke *d.SmokeResult,
	findings []d.FindingRaw,
	patterns []d.ASTCodePattern,
	profile *d.TargetProfile,
	runMode d.RunMode,
) d.IntelEndpoint {
	auth := resolveAuth(ep, authEntry, profile)

	if runMode == d.RunModeOffline {
		return buildOfflineEndpointIntel(ep, baseURL, auth, patterns, profile)
	}

	whatItDoes := buildWhatItDoes(ep, evidence, contract, smoke)
	inputs := buildInputs(ep, evidence, contract, annot)
	outputs := buildOutputs(ep, evidence, contract)

	cmdCtx := commandContext{
		baseURL:     baseURL,
		ep:          ep,
		authInfo:    IntelAuthInfo{Required: auth.Required, Mechanism: auth.Mechanism, HeaderKey: resolveAuthHeaderKey(profile)},
		evidence:    evidence,
		contract:    contract,
		annotations: annot,
	}
	readyCommands, _ := buildReadyCommands(cmdCtx)
	queryVariants := buildQueryVariants(cmdCtx)

	var warnings []string
	if auth.Required == "unknown" {
		warnings = append(warnings, "Auth status unknown; validate with auth_matrix before using in production.")
	}
	if len(evidence) == 0 {
		warnings = append(warnings, "No runtime evidence available; commands are based on AST/schema only.")
	}
	for _, v := range queryVariants {
		if v.Source == "inferred_heuristic" {
			warnings = append(warnings, fmt.Sprintf("Variant '%s' is inferred; may not be supported.", v.VariantName))
		}
	}

	howToQuery := d.IntelHowToQuery{
		Goal:          buildQueryGoal(ep),
		ReadyCommands: readyCommands,
		QueryVariants: queryVariants,
		Warnings:      warnings,
	}

	tests := buildSuggestedTests(ep, auth, evidence)
	secNotes := buildSecurityNotes(ep, findings, patterns, evidence)

	var astRefs []d.ASTRef
	if ep.HandlerRef != nil {
		astRefs = append(astRefs, *ep.HandlerRef)
	}
	if ep.GroupRef != nil {
		astRefs = append(astRefs, *ep.GroupRef)
	}
	astRefs = append(astRefs, ep.Middlewares...)

	var evidenceRefs []string
	for _, e := range evidence {
		evidenceRefs = append(evidenceRefs, e.EvidenceID)
	}

	return d.IntelEndpoint{
		EndpointID:        ep.EndpointID,
		Method:            ep.Method,
		PathTemplate:      ep.Path,
		OperationID:       buildOperationID(ep),
		Tags:              ep.Tags,
		Auth:              auth,
		WhatItDoes:        whatItDoes,
		Inputs:            inputs,
		Outputs:           outputs,
		HowToQuery:        howToQuery,
		TestsYouShouldRun: tests,
		SecurityNotes:     secNotes,
		ASTRefs:           astRefs,
		EvidenceRefs:      evidenceRefs,
	}
}

func buildOfflineEndpointIntel(ep d.EndpointEntry, baseURL string, auth d.IntelAuth, patterns []d.ASTCodePattern, profile *d.TargetProfile) d.IntelEndpoint {
	handlerName := ""
	if ep.HandlerRef != nil {
		handlerName = ep.HandlerRef.Label
	}

	summary := inferSummaryFromNaming(ep.Method, ep.Path, handlerName)

	whatItDoes := d.IntelWhatItDoes{
		Summary:    "OFFLINE - Could not test. " + summary,
		Detailed:   "Service was unreachable during this run. Only AST-based information is available. What we know from code analysis: " + summary,
		Confidence: 0.2,
		Facts: []d.IntelFact{{
			Text: "Service returned connection errors; endpoint could not be probed at runtime.",
		}},
	}

	if handlerName != "" {
		whatItDoes.Inferences = append(whatItDoes.Inferences, d.IntelInference{
			Text:            fmt.Sprintf("Handler '%s' suggests this endpoint's purpose, but behavior is unconfirmed.", handlerName),
			RuleOfInference: "handler_naming",
			Confidence:      0.3,
			ASTRefs:         astRefsFromEntry(ep),
		})
	}

	inputs := d.IntelInputs{PathParams: extractPathParams(ep.Path)}

	howToQuery := d.IntelHowToQuery{
		Goal: "Service was offline. Use the Try It playground to test this endpoint once the service is running.",
		Warnings: []string{
			"SERVICE OFFLINE: No runtime evidence available.",
			"Commands are AST-only; expected responses are unknown.",
			"Use the Try It playground to send a real request and verify behavior.",
		},
	}

	url := strings.TrimRight(baseURL, "/") + ep.Path
	cmd := fmt.Sprintf("curl -s -w '\\n%%{http_code}' '%s'", url)
	howToQuery.ReadyCommands = append(howToQuery.ReadyCommands, d.IntelReadyCommand{
		Name:    "curl_connectivity_test",
		Kind:    "curl",
		Command: cmd,
		BasedOn: "ast_only",
		Notes:   "Test if endpoint is reachable. Service was offline during analysis.",
	})

	var astRefs []d.ASTRef
	if ep.HandlerRef != nil {
		astRefs = append(astRefs, *ep.HandlerRef)
	}

	secNotes := buildSecurityNotes(ep, nil, patterns, nil)

	return d.IntelEndpoint{
		EndpointID:   ep.EndpointID,
		Method:       ep.Method,
		PathTemplate: ep.Path,
		OperationID:  buildOperationID(ep),
		Tags:         ep.Tags,
		Auth:         auth,
		WhatItDoes:   whatItDoes,
		Inputs:       inputs,
		Outputs:      d.IntelOutputs{},
		HowToQuery:   howToQuery,
		TestsYouShouldRun: []d.IntelTest{{
			Name:       "connectivity_check",
			Why:        "Service was offline. First verify the endpoint is reachable.",
			Importance: "high",
		}},
		SecurityNotes: secNotes,
		ASTRefs:       astRefs,
	}
}

func resolveAuth(ep d.EndpointEntry, authEntry *d.AuthMatrixEntry, profile *d.TargetProfile) d.IntelAuth {
	auth := d.IntelAuth{
		Required:  "unknown",
		From:      "unknown",
		Mechanism: "unknown",
	}

	hasMiddlewareAuth := false
	for _, mw := range ep.Middlewares {
		name := strings.ToLower(mw.Label)
		if strings.Contains(name, "auth") || strings.Contains(name, "jwt") || strings.Contains(name, "token") {
			hasMiddlewareAuth = true
			if strings.Contains(name, "jwt") {
				auth.Mechanism = "jwt"
			} else if strings.Contains(name, "key") || strings.Contains(name, "apikey") {
				auth.Mechanism = "api_key"
			}
		}
	}

	if authEntry != nil {
		if authEntry.NoAuth == d.AuthDenied {
			auth.Required = "yes"
			auth.From = "runtime"
		} else if authEntry.NoAuth == d.AuthAllowed {
			auth.Required = "no"
			auth.From = "runtime"
		}

		if hasMiddlewareAuth && auth.Required == "no" {
			auth.Notes = "AST shows auth middleware but runtime allows unauthenticated access. Possible discrepancy."
			auth.From = "both"
		} else if hasMiddlewareAuth && auth.Required == "yes" {
			auth.From = "both"
		}
	} else if hasMiddlewareAuth {
		auth.Required = "yes"
		auth.From = "ast"
	}

	if profile != nil && len(profile.AuthHints.Mechanisms) > 0 && auth.Mechanism == "unknown" {
		mech := strings.ToLower(profile.AuthHints.Mechanisms[0])
		if strings.Contains(mech, "jwt") || strings.Contains(mech, "bearer") {
			auth.Mechanism = "jwt"
		} else if strings.Contains(mech, "key") || strings.Contains(mech, "apikey") {
			auth.Mechanism = "api_key"
		}
	}

	if profile != nil && len(profile.AuthHints.HeadersSeen) > 0 && auth.Mechanism == "unknown" {
		for _, h := range profile.AuthHints.HeadersSeen {
			if strings.Contains(strings.ToLower(h), "key") {
				auth.Mechanism = "api_key"
				break
			}
		}
	}

	return auth
}

func resolveAuthHeaderKey(profile *d.TargetProfile) string {
	if profile == nil {
		return ""
	}
	for _, h := range profile.AuthHints.HeadersSeen {
		if isAuthHeader(h) {
			return h
		}
	}
	return ""
}

func buildWhatItDoes(ep d.EndpointEntry, evidence []d.EvidenceSample, contract *d.InferredContract, smoke *d.SmokeResult) d.IntelWhatItDoes {
	result := d.IntelWhatItDoes{Confidence: 0.3}

	handlerName := ""
	if ep.HandlerRef != nil {
		handlerName = ep.HandlerRef.Label
	}

	summary := inferSummaryFromNaming(ep.Method, ep.Path, handlerName)
	result.Summary = summary

	var detailed []string
	detailed = append(detailed, summary)

	if handlerName != "" {
		result.Inferences = append(result.Inferences, d.IntelInference{
			Text:            fmt.Sprintf("Handler name '%s' suggests this endpoint's purpose.", handlerName),
			RuleOfInference: "handler_naming",
			Confidence:      0.5,
			ASTRefs:         astRefsFromEntry(ep),
		})
		detailed = append(detailed, fmt.Sprintf("The handler '%s' is registered in the router.", handlerName))
		result.Confidence = 0.5
	}

	if len(ep.Middlewares) > 0 {
		var names []string
		for _, mw := range ep.Middlewares {
			names = append(names, mw.Label)
		}
		detailed = append(detailed, fmt.Sprintf("Applied middlewares: %s.", strings.Join(names, ", ")))
	}

	if smoke != nil {
		if smoke.Passed {
			result.Facts = append(result.Facts, d.IntelFact{
				Text:         fmt.Sprintf("Smoke test passed with status %d.", smoke.StatusCode),
				EvidenceRefs: smoke.EvidenceRefs,
			})
			result.Confidence = maxf(result.Confidence, 0.7)
			detailed = append(detailed, fmt.Sprintf("Responded with status %d during smoke testing.", smoke.StatusCode))
		} else if smoke.BlockReason != "" {
			result.Facts = append(result.Facts, d.IntelFact{
				Text:         fmt.Sprintf("Smoke test blocked: %s.", smoke.BlockReason),
				EvidenceRefs: smoke.EvidenceRefs,
			})
		}
	}

	if contract != nil {
		if len(contract.ResponseSchemas) > 0 {
			for _, rs := range contract.ResponseSchemas {
				result.Facts = append(result.Facts, d.IntelFact{
					Text:         fmt.Sprintf("Returns status %d with content-type %s (schema: %s).", rs.Status, rs.ContentType, rs.SchemaRef),
					EvidenceRefs: contract.EvidenceRefs,
				})
			}
			result.Confidence = maxf(result.Confidence, 0.8)
		}
	}

	successSample := findSuccessEvidence(evidence)
	if successSample != nil && successSample.Response != nil {
		bodySnip := successSample.Response.BodySnippet
		if len(bodySnip) > 200 {
			bodySnip = bodySnip[:200] + "..."
		}
		if bodySnip != "" {
			detailed = append(detailed, fmt.Sprintf("Response body sample available (status %d).", successSample.Response.Status))
			result.Confidence = maxf(result.Confidence, 0.85)
		}
	}

	result.Detailed = strings.Join(detailed, " ")
	return result
}

func inferSummaryFromNaming(method, path, handler string) string {
	resource := extractResourceName(path)
	if resource == "" {
		resource = "resource"
	}
	isCollection := !hasPathParam(path)

	switch method {
	case "GET":
		if isCollection {
			return fmt.Sprintf("Lists %s.", resource)
		}
		return fmt.Sprintf("Retrieves a specific %s by identifier.", singularize(resource))
	case "POST":
		return fmt.Sprintf("Creates a new %s.", singularize(resource))
	case "PUT":
		return fmt.Sprintf("Replaces a %s.", singularize(resource))
	case "PATCH":
		return fmt.Sprintf("Partially updates a %s.", singularize(resource))
	case "DELETE":
		return fmt.Sprintf("Deletes a %s.", singularize(resource))
	default:
		return fmt.Sprintf("Operates on %s via %s.", resource, method)
	}
}

func buildInputs(ep d.EndpointEntry, evidence []d.EvidenceSample, contract *d.InferredContract, annot *d.SemanticAnnotation) d.IntelInputs {
	inputs := d.IntelInputs{}

	inputs.PathParams = extractPathParams(ep.Path)

	if contract != nil && contract.RequestSchema != nil {
		for _, qp := range contract.RequestSchema.QueryParams {
			inputs.QueryParams = append(inputs.QueryParams, d.IntelQueryParam{
				Name:       qp,
				Type:       "unknown",
				Source:     "runtime",
				Confidence: contract.Confidence,
			})
		}

		for _, h := range contract.RequestSchema.Headers {
			inputs.Headers = append(inputs.Headers, d.IntelHeader{
				Name:       h,
				Required:   "unknown",
				Source:     "runtime",
				Confidence: contract.Confidence,
			})
		}

		if contract.RequestSchema.ContentType != "" && len(contract.RequestSchema.Fields) > 0 {
			body := &d.IntelBody{
				ContentType: contract.RequestSchema.ContentType,
				SchemaRef:   contract.RequestSchema.SchemaRef,
			}
			for _, f := range contract.RequestSchema.Fields {
				body.RequiredFields = append(body.RequiredFields, d.IntelBodyField{
					FieldPath:  f.Name,
					Type:       f.Type,
					Source:     "runtime",
					Confidence: contract.Confidence,
				})
			}
			inputs.Body = body
		}
	}

	if len(evidence) > 0 {
		observedHeaders := make(map[string][]string)
		for _, e := range evidence {
			for k, v := range e.Request.Headers {
				lk := strings.ToLower(k)
				if lk == "host" || lk == "user-agent" || lk == "accept-encoding" || lk == "content-length" {
					continue
				}
				existing := observedHeaders[k]
				found := false
				for _, ev := range existing {
					if ev == v {
						found = true
						break
					}
				}
				if !found && len(existing) < 3 {
					observedHeaders[k] = append(existing, v)
				}
			}
		}

		for name, vals := range observedHeaders {
			exists := false
			for _, h := range inputs.Headers {
				if strings.EqualFold(h.Name, name) {
					exists = true
					break
				}
			}
			if !exists {
				inputs.Headers = append(inputs.Headers, d.IntelHeader{
					Name:           name,
					Required:       "unknown",
					ObservedValues: vals,
					Source:         "runtime",
					Confidence:     0.8,
				})
			}
		}

		if inputs.Body == nil && isBodyMethod(ep.Method) {
			for _, e := range evidence {
				if e.Request.Body != "" {
					inputs.Body = &d.IntelBody{
						ContentType:        e.Request.ContentType,
						ExampleEvidenceRef: e.EvidenceID,
						Notes:              "Body structure observed from evidence",
					}
					break
				}
			}
		}
	}

	return inputs
}

func buildOutputs(ep d.EndpointEntry, evidence []d.EvidenceSample, contract *d.InferredContract) d.IntelOutputs {
	outputs := d.IntelOutputs{}

	if contract != nil {
		for _, rs := range contract.ResponseSchemas {
			outputs.Responses = append(outputs.Responses, d.IntelResponse{
				Status:      rs.Status,
				ContentType: rs.ContentType,
				SchemaRef:   rs.SchemaRef,
				WhatYouGet:  fmt.Sprintf("Returns status %d with %s content.", rs.Status, rs.ContentType),
				ExampleRef:  rs.ExampleRef,
			})
		}
	}

	seenStatus := make(map[int]bool)
	for _, r := range outputs.Responses {
		seenStatus[r.Status] = true
	}

	for _, e := range evidence {
		if e.Response == nil {
			continue
		}
		st := e.Response.Status
		if seenStatus[st] {
			continue
		}
		seenStatus[st] = true

		if st >= 200 && st < 400 {
			desc := "Success response."
			if e.Response.BodySnippet != "" {
				bodyPeek := e.Response.BodySnippet
				if len(bodyPeek) > 150 {
					bodyPeek = bodyPeek[:150] + "..."
				}
				desc = fmt.Sprintf("Returns %s content with response body.", e.Response.ContentType)
			}
			outputs.Responses = append(outputs.Responses, d.IntelResponse{
				Status:      st,
				ContentType: e.Response.ContentType,
				WhatYouGet:  desc,
				ExampleRef:  e.EvidenceID,
			})
		} else if st >= 400 {
			meaning := httpStatusMeaning(st)
			outputs.CommonErrors = append(outputs.CommonErrors, d.IntelCommonError{
				Status:     st,
				Meaning:    meaning,
				ExampleRef: e.EvidenceID,
			})
		}
	}

	return outputs
}

func buildSuggestedTests(ep d.EndpointEntry, auth d.IntelAuth, evidence []d.EvidenceSample) []d.IntelTest {
	var tests []d.IntelTest

	if auth.Required != "no" {
		tests = append(tests, d.IntelTest{
			Name:       "no_auth_check",
			Why:        "Verify that endpoint correctly rejects unauthenticated requests.",
			Importance: "high",
		})
	}

	if isBodyMethod(ep.Method) {
		tests = append(tests, d.IntelTest{
			Name:       "empty_body_check",
			Why:        "Verify endpoint handles missing/empty body gracefully.",
			Importance: "medium",
		})
		tests = append(tests, d.IntelTest{
			Name:       "malformed_json_check",
			Why:        "Verify endpoint returns proper error for malformed input.",
			Importance: "medium",
		})
	}

	if hasPathParam(ep.Path) {
		tests = append(tests, d.IntelTest{
			Name:       "invalid_id_check",
			Why:        "Verify endpoint handles non-existent/invalid identifiers properly.",
			Importance: "high",
		})
	}

	return tests
}

func buildSecurityNotes(ep d.EndpointEntry, findings []d.FindingRaw, patterns []d.ASTCodePattern, evidence []d.EvidenceSample) d.IntelSecurityNotes {
	notes := d.IntelSecurityNotes{}

	for _, f := range findings {
		sev := "medium"
		switch f.Severity {
		case d.SeverityCritical:
			sev = "high"
		case d.SeverityHigh:
			sev = "high"
		case d.SeverityLow, d.SeverityInfo:
			sev = "low"
		}
		notes.Exposures = append(notes.Exposures, d.IntelExposure{
			Text:         f.Title + ": " + f.Description,
			Severity:     sev,
			EvidenceRefs: f.EvidenceRefs,
		})
	}

	for _, p := range patterns {
		notes.ASTCodePatternsRel = append(notes.ASTCodePatternsRel, d.IntelASTPattern{
			Pattern:                p.Pattern,
			ASTRef:                 p.ASTRef,
			OnlyIfCorrelatedWithRT: true,
		})
	}

	return notes
}

func buildQueryGoal(ep d.EndpointEntry) string {
	resource := extractResourceName(ep.Path)
	if resource == "" {
		resource = "this endpoint"
	}
	switch ep.Method {
	case "GET":
		if hasPathParam(ep.Path) {
			return fmt.Sprintf("Fetch a specific %s by its identifier. Verify the response structure and status code.", singularize(resource))
		}
		return fmt.Sprintf("List or search %s. Use query parameters for filtering and pagination if supported.", resource)
	case "POST":
		return fmt.Sprintf("Create a new %s. Send the required fields in the request body and verify the created resource is returned.", singularize(resource))
	case "PUT", "PATCH":
		return fmt.Sprintf("Update an existing %s. Send only the fields to modify and verify the updated resource is returned.", singularize(resource))
	case "DELETE":
		return fmt.Sprintf("Delete a %s. Verify the resource is removed and proper status code is returned.", singularize(resource))
	default:
		return fmt.Sprintf("Execute %s on %s.", ep.Method, resource)
	}
}

func buildDomainDescription(dom *d.IntelDomain) string {
	methods := make(map[string]int)
	for _, ep := range dom.Endpoints {
		methods[ep.Method]++
	}

	var methodParts []string
	for m, c := range methods {
		methodParts = append(methodParts, fmt.Sprintf("%d %s", c, m))
	}

	return fmt.Sprintf(
		"The '%s' domain groups %d endpoints (%s). "+
			"These endpoints are classified together based on %s. "+
			"This domain covers operations related to %s management and interaction.",
		dom.DomainName, len(dom.Endpoints), strings.Join(methodParts, ", "),
		dom.DomainBasis, dom.DomainName,
	)
}

func buildOpenQuestions(dossier *d.DossierV2Full) []d.IntelOpenQuestion {
	var questions []d.IntelOpenQuestion

	if dossier.RunMode == d.RunModeOffline {
		questions = append(questions, d.IntelOpenQuestion{
			Question:   "Service was OFFLINE during this run. No runtime evidence could be collected.",
			WhyMissing: "All or most connection attempts failed. The API server may not be running or is unreachable from this environment.",
			Priority:   "high",
		})
		questions = append(questions, d.IntelOpenQuestion{
			Question:   "Use the Try It playground to manually test connectivity and collect evidence.",
			WhyMissing: "Manual verification is needed to confirm the service can be reached.",
			Priority:   "high",
		})
		return questions
	}

	if dossier.Runtime.AuthMatrix == nil {
		questions = append(questions, d.IntelOpenQuestion{
			Question:   "Authentication mechanisms could not be determined for any endpoint.",
			WhyMissing: "Auth matrix was not generated, possibly due to runtime errors.",
			Priority:   "high",
		})
	}

	if len(dossier.Runtime.InferredContracts) == 0 {
		questions = append(questions, d.IntelOpenQuestion{
			Question:   "Request/response contracts could not be inferred for any endpoint.",
			WhyMissing: "No successful responses were captured during the run.",
			Priority:   "high",
		})
	}

	unreachable := 0
	for _, s := range dossier.Runtime.SmokeResults {
		if !s.Passed && s.BlockReason != "" {
			unreachable++
		}
	}
	if unreachable > 0 {
		questions = append(questions, d.IntelOpenQuestion{
			Question:   fmt.Sprintf("%d endpoints were unreachable during testing.", unreachable),
			WhyMissing: "Connection refused or timeout during smoke testing.",
			Priority:   "medium",
		})
	}

	for _, disc := range dossier.Runtime.Discrepancies.ASTvsRuntime {
		questions = append(questions, d.IntelOpenQuestion{
			Question:   fmt.Sprintf("AST↔Runtime discrepancy on %s %s: %s", disc.Method, disc.Path, disc.Description),
			WhyMissing: disc.Description,
			Priority:   "medium",
		})
	}

	return questions
}

// --- Indexing helpers ---

func indexEvidenceByEndpoint(samples []d.EvidenceSample) map[string][]d.EvidenceSample {
	m := make(map[string][]d.EvidenceSample)
	for _, s := range samples {
		if s.EndpointID != "" {
			m[s.EndpointID] = append(m[s.EndpointID], s)
		}
	}
	return m
}

func indexContractsByEndpoint(contracts []d.InferredContract) map[string]*d.InferredContract {
	m := make(map[string]*d.InferredContract)
	for i := range contracts {
		m[contracts[i].EndpointID] = &contracts[i]
	}
	return m
}

func indexAnnotationsByEndpoint(annots []d.SemanticAnnotation) map[string]*d.SemanticAnnotation {
	m := make(map[string]*d.SemanticAnnotation)
	for i := range annots {
		m[annots[i].EndpointID] = &annots[i]
	}
	return m
}

func indexAuthByEndpoint(matrix *d.AuthMatrix) map[string]*d.AuthMatrixEntry {
	m := make(map[string]*d.AuthMatrixEntry)
	if matrix == nil {
		return m
	}
	for i := range matrix.Entries {
		m[matrix.Entries[i].EndpointID] = &matrix.Entries[i]
	}
	return m
}

func indexSmokeByEndpoint(results []d.SmokeResult) map[string]*d.SmokeResult {
	m := make(map[string]*d.SmokeResult)
	for i := range results {
		m[results[i].EndpointID] = &results[i]
	}
	return m
}

func indexFindingsByEndpoint(findings []d.FindingRaw) map[string][]d.FindingRaw {
	m := make(map[string][]d.FindingRaw)
	for _, f := range findings {
		if f.EndpointID != "" {
			m[f.EndpointID] = append(m[f.EndpointID], f)
		}
	}
	return m
}

func indexPatternsByEndpoint(patterns []d.ASTCodePattern, endpoints []d.EndpointEntry) map[string][]d.ASTCodePattern {
	m := make(map[string][]d.ASTCodePattern)
	handlerFiles := make(map[string]string)
	for _, ep := range endpoints {
		if ep.HandlerRef != nil {
			handlerFiles[ep.HandlerRef.Location.File] = ep.EndpointID
		}
	}
	for _, p := range patterns {
		if epID, ok := handlerFiles[p.ASTRef.Location.File]; ok {
			m[epID] = append(m[epID], p)
		}
	}
	return m
}

// --- Utilities ---

func extractResourceName(path string) string {
	parts := strings.Split(strings.Trim(path, "/"), "/")
	for i := len(parts) - 1; i >= 0; i-- {
		p := parts[i]
		if strings.HasPrefix(p, "{") || strings.HasPrefix(p, ":") || isVersionSegment(p) || p == "api" {
			continue
		}
		return p
	}
	return ""
}

func hasPathParam(path string) bool {
	return strings.Contains(path, "{") || strings.Contains(path, ":")
}

func singularize(s string) string {
	if strings.HasSuffix(s, "ies") {
		return strings.TrimSuffix(s, "ies") + "y"
	}
	if strings.HasSuffix(s, "ses") || strings.HasSuffix(s, "xes") || strings.HasSuffix(s, "zes") {
		return strings.TrimSuffix(s, "es")
	}
	if strings.HasSuffix(s, "s") && !strings.HasSuffix(s, "ss") {
		return strings.TrimSuffix(s, "s")
	}
	return s
}

func extractPathParams(path string) []d.IntelParam {
	var params []d.IntelParam
	parts := strings.Split(path, "/")
	for _, p := range parts {
		if strings.HasPrefix(p, "{") && strings.HasSuffix(p, "}") {
			name := strings.Trim(p, "{}")
			params = append(params, d.IntelParam{
				Name:       name,
				Type:       guessParamType(name),
				Meaning:    fmt.Sprintf("Identifier for the %s.", name),
				Source:     "ast",
				Confidence: 0.9,
			})
		} else if strings.HasPrefix(p, ":") {
			name := strings.TrimPrefix(p, ":")
			params = append(params, d.IntelParam{
				Name:       name,
				Type:       guessParamType(name),
				Meaning:    fmt.Sprintf("Identifier for the %s.", name),
				Source:     "ast",
				Confidence: 0.9,
			})
		}
	}
	return params
}

func guessParamType(name string) string {
	ln := strings.ToLower(name)
	if strings.Contains(ln, "uuid") {
		return "uuid"
	}
	if ln == "id" || strings.HasSuffix(ln, "_id") || strings.HasSuffix(ln, "id") {
		return "string"
	}
	return "string"
}

func buildOperationID(ep d.EndpointEntry) string {
	if ep.HandlerRef != nil && ep.HandlerRef.Extra.Symbol != "" {
		return ep.HandlerRef.Extra.Symbol
	}
	if ep.HandlerRef != nil && ep.HandlerRef.Label != "" {
		label := ep.HandlerRef.Label
		label = strings.ReplaceAll(label, ".", "_")
		label = strings.ReplaceAll(label, "/", "_")
		return label
	}
	resource := extractResourceName(ep.Path)
	return strings.ToLower(ep.Method) + "_" + resource
}

func astRefsFromEntry(ep d.EndpointEntry) []d.ASTRef {
	var refs []d.ASTRef
	if ep.HandlerRef != nil {
		refs = append(refs, *ep.HandlerRef)
	}
	return refs
}

func httpStatusMeaning(status int) string {
	meanings := map[int]string{
		400: "Bad request: invalid input or missing required fields.",
		401: "Unauthorized: authentication required or invalid credentials.",
		403: "Forbidden: authenticated but insufficient permissions.",
		404: "Not found: resource does not exist.",
		405: "Method not allowed.",
		409: "Conflict: resource already exists or state conflict.",
		422: "Unprocessable entity: validation error.",
		429: "Too many requests: rate limit exceeded.",
		500: "Internal server error.",
		502: "Bad gateway.",
		503: "Service unavailable.",
	}
	if m, ok := meanings[status]; ok {
		return m
	}
	return fmt.Sprintf("HTTP %d response.", status)
}

func maxf(a, b float64) float64 {
	if a > b {
		return a
	}
	return b
}
