FROM golang:1.25-alpine
RUN apk add --no-cache gcc musl-dev git
RUN go install github.com/air-verse/air@latest
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
EXPOSE 8090
CMD ["air", "-c", ".air.toml"]
