package repoaudit

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var (
	requestsCallRE = regexp.MustCompile(`requests\.(get|post|put|patch|delete|request)\s*\(`)
	envIndexRE     = regexp.MustCompile(`os\.environ\[[^]]+\]`)
	sqlIDColumnRE  = regexp.MustCompile(`(?i)\b([a-zA-Z0-9_]+_id)\b`)
	whereColumnRE  = regexp.MustCompile(`(?i)\bWHERE\s+([a-zA-Z0-9_.]+)\s*=`)
)

func buildRepoFindings(auditID string, inv Inventory) []Finding {
	var findings []Finding
	if _, ok := inv.Stack["node"]; ok && !hasAnyFile(inv.Files, "package-lock.json", "yarn.lock", "pnpm-lock.yaml") {
		findings = append(findings, newFinding(auditID, "node.no_lockfile", "Informative", "P3", "Hipótesis", "dependencies", "Node project has no lockfile", "package.json was detected but no npm/yarn/pnpm lockfile was found in the scanned source set.", "Media", "package.json", 0, Evidence{Kind: "manifest", FilePath: "package.json", Summary: "Node manifest exists without a detected package lockfile."}, FindingDetails{
			WhyProblem:            "Without a lockfile, dependency resolution can drift across machines.",
			Impact:                "Builds may become non-reproducible even when package.json is unchanged.",
			RiskOfChange:          "Low if the project already has a preferred package manager.",
			MinimumRecommendation: "Commit the package manager lockfile generated by the current dependency set.",
			Avoid:                 "Do not switch package managers only to create a lockfile.",
			Validation:            "Run the package manager install command and confirm the next audit detects the lockfile.",
		}))
	}
	return findings
}

func buildGoFindings(auditID, root string, inv Inventory) []Finding {
	if _, ok := inv.Stack["go"]; !ok {
		return nil
	}
	var findings []Finding
	for _, rel := range inv.Files {
		if !strings.HasSuffix(rel, ".go") || strings.HasSuffix(rel, "_test.go") {
			continue
		}
		lines, ok := readLines(root, rel)
		if !ok {
			continue
		}
		content := strings.Join(lines, "\n")
		for i, line := range lines {
			trimmed := strings.TrimSpace(line)
			if strings.Contains(trimmed, "http.ListenAndServe(") || strings.Contains(trimmed, "http.Serve(") {
				if !strings.Contains(content, "ReadHeaderTimeout") && !strings.Contains(content, "ReadTimeout") && !strings.Contains(content, "WriteTimeout") && !strings.Contains(content, "IdleTimeout") {
					findings = append(findings, newFinding(auditID, "go.http_server_without_timeouts", "Medium", "P2", "Probable", "go", "HTTP server appears to run without explicit timeouts", "A Go HTTP server entrypoint was detected without nearby http.Server timeout configuration in the same file.", "Media", rel, i+1, Evidence{Kind: "source", FilePath: rel, Line: i + 1, Summary: strings.TrimSpace(line)}, FindingDetails{
						WhyProblem:            "Go HTTP servers without timeouts are more exposed to slow clients and resource exhaustion.",
						Impact:                "A production process can hold connections longer than intended under network pressure.",
						RiskOfChange:          "Medium; timeout values affect long-lived requests and should be chosen conservatively.",
						MinimumRecommendation: "Wrap the handler in http.Server and configure ReadHeaderTimeout plus sensible read/write/idle timeouts.",
						Avoid:                 "Do not change routes or handler behavior while adding server timeouts.",
						Validation:            "Run go test and start the server locally with the same address configuration.",
					}))
				}
			}
			if strings.Contains(trimmed, "go func") && suspiciousGoRoutineFile(rel) && !lineWindowContains(lines, i, 12, "ctx") && !lineWindowContains(lines, i, 12, "WaitGroup") {
				findings = append(findings, newFinding(auditID, "go.uncontrolled_goroutine", "Informative", "P3", "Hipótesis", "go", "Goroutine may not be tied to context or wait lifecycle", "A goroutine was detected in a runtime-facing file without obvious context cancellation or wait coordination nearby.", "Baja", rel, i+1, Evidence{Kind: "source", FilePath: rel, Line: i + 1, Summary: strings.TrimSpace(line)}, FindingDetails{
					WhyProblem:            "Detached goroutines can outlive requests or hide failures.",
					Impact:                "Leaks and silent background failures are possible if the surrounding lifecycle is missing.",
					RiskOfChange:          "Medium; concurrency changes can alter timing.",
					MinimumRecommendation: "Review whether the goroutine should receive context cancellation or be coordinated by a worker lifecycle.",
					Avoid:                 "Do not inline or remove concurrency without proving behavior is unchanged.",
					Validation:            "Add/confirm tests around cancellation or worker shutdown before changing it.",
				}))
			}
			if ignoredCriticalError(trimmed) {
				findings = append(findings, newFinding(auditID, "go.ignored_io_or_persistence_error", "Informative", "P3", "Hipótesis", "go", "Potentially important error is ignored", "The line ignores an error from an IO, persistence or command operation.", "Media", rel, i+1, Evidence{Kind: "source", FilePath: rel, Line: i + 1, Summary: strings.TrimSpace(line)}, FindingDetails{
					WhyProblem:            "Ignoring IO or persistence errors can hide failed writes, commands or decoding.",
					Impact:                "The system may report success while a side effect failed.",
					RiskOfChange:          "Low to medium; surfacing the error may change API responses.",
					MinimumRecommendation: "Return, wrap or log the error where it affects observable behavior.",
					Avoid:                 "Do not mechanically replace every ignored error without understanding intent.",
					Validation:            "Add a focused failure-path test for the operation if it is user-visible.",
				}))
			}
		}
		findings = append(findings, goTransactionFindings(auditID, rel, lines)...)
	}
	return findings
}

func goTransactionFindings(auditID, rel string, lines []string) []Finding {
	var findings []Finding
	for i, line := range lines {
		if !strings.Contains(line, ".Begin(") && !strings.Contains(line, ".BeginTx(") {
			continue
		}
		window := strings.Join(windowLines(lines, i, 80), "\n")
		hasCommit := strings.Contains(window, ".Commit(")
		hasRollback := strings.Contains(window, ".Rollback(")
		if hasCommit && hasRollback {
			continue
		}
		title := "Transaction does not show both Commit and Rollback nearby"
		priority := "P2"
		if hasCommit && !hasRollback {
			priority = "P1"
		}
		findings = append(findings, newFinding(auditID, "go.transaction_missing_commit_or_rollback", "Medium", priority, "Probable", "go", title, "A transaction begin call was detected without both commit and rollback calls in the following function-sized window.", "Media", rel, i+1, Evidence{Kind: "source", FilePath: rel, Line: i + 1, Summary: strings.TrimSpace(line)}, FindingDetails{
			WhyProblem:            "Transactions need an explicit success and failure path to avoid leaked transactions or partial writes.",
			Impact:                "Database connections can be held longer than expected or writes can be left ambiguous.",
			RiskOfChange:          "Medium; transaction fixes can affect data-write behavior.",
			MinimumRecommendation: "Add a rollback-on-error path and keep commit only on success.",
			Avoid:                 "Do not broaden transaction scope while fixing lifecycle handling.",
			Validation:            "Add a repository/usecase test that forces an error after Begin and verifies rollback behavior.",
		}))
	}
	return findings
}

func buildReactFindings(auditID, root string, inv Inventory) []Finding {
	if _, ok := inv.Stack["react"]; !ok {
		return nil
	}
	var findings []Finding
	if scripts, ok := readPackageScripts(root); ok {
		if _, hasBuild := scripts["build"]; !hasBuild {
			findings = append(findings, reactScriptFinding(auditID, "react.no_build_script", "build"))
		}
		if _, hasTypecheck := scripts["typecheck"]; !hasTypecheck {
			findings = append(findings, reactScriptFinding(auditID, "react.no_typecheck_script", "typecheck"))
		}
	}
	for _, rel := range inv.Files {
		if !isJSLike(rel) {
			continue
		}
		lines, ok := readLines(root, rel)
		if !ok {
			continue
		}
		for i, line := range lines {
			if containsAPICall(line) && !isCentralAPIFile(rel) {
				state := "Hipótesis"
				priority := "P3"
				if strings.Contains(rel, "pages/") || strings.Contains(rel, "components/") {
					state = "Probable"
					priority = "P2"
				}
				desc := "A direct API call was detected outside the central API client."
				if !lineWindowContains(lines, i, 8, "catch") && !lineWindowContains(lines, i, 8, "try") {
					desc += " No nearby catch/try block was visible in the scanned window."
				}
				findings = append(findings, newFinding(auditID, "react.direct_api_call_outside_client", "Low", priority, state, "react", "Direct API call outside client module", desc, "Media", rel, i+1, Evidence{Kind: "source", FilePath: rel, Line: i + 1, Summary: strings.TrimSpace(line)}, FindingDetails{
					WhyProblem:            "Scattered API calls make loading/error handling and backend contracts harder to audit.",
					Impact:                "Frontend behavior can diverge between screens and miss shared retry/error policy.",
					RiskOfChange:          "Medium; moving calls can alter component state timing.",
					MinimumRecommendation: "Route the call through the existing API client with the same request/response contract.",
					Avoid:                 "Do not introduce a new API abstraction parallel to the existing client.",
					Validation:            "Run typecheck/build and verify the screen still renders the same data.",
				}))
			}
			if strings.Contains(line, "useEffect(") && effectWindowSuspicious(lines, i) {
				findings = append(findings, newFinding(auditID, "react.suspicious_effect_dependencies", "Informative", "P3", "Hipótesis", "react", "useEffect dependencies may be incomplete around API call", "A useEffect block appears to call an API with an empty dependency array or no visible dependency list in the local window.", "Baja", rel, i+1, Evidence{Kind: "source", FilePath: rel, Line: i + 1, Summary: strings.TrimSpace(line)}, FindingDetails{
					WhyProblem:            "Effects with incomplete dependencies can fetch stale data or miss updates.",
					Impact:                "Screens may not refresh when inputs change.",
					RiskOfChange:          "Medium; dependency changes can create extra renders or requests.",
					MinimumRecommendation: "Review the effect inputs and add only the dependencies required by the existing behavior.",
					Avoid:                 "Do not blindly auto-fix dependency arrays without checking request semantics.",
					Validation:            "Run typecheck/build and manually verify the affected screen during product testing.",
				}))
			}
		}
	}
	return findings
}

func reactScriptFinding(auditID, ruleID, script string) Finding {
	return newFinding(auditID, ruleID, "Medium", "P2", "Probable", "react", "React project has no "+script+" script", "package.json was detected for a React project but scripts."+script+" was not found.", "Alta", "package.json", 0, Evidence{Kind: "manifest", FilePath: "package.json", Summary: "Missing scripts." + script + " in package.json."}, FindingDetails{
		WhyProblem:            "Without a standard script, ToolLab and CI cannot run this validation consistently.",
		Impact:                "Frontend regressions may be missed before runtime.",
		RiskOfChange:          "Low if the script maps to existing tooling.",
		MinimumRecommendation: "Add a package.json " + script + " script using the current project tooling.",
		Avoid:                 "Do not add a script that performs unrelated formatting or dependency installation.",
		Validation:            "Run npm run " + script + " locally.",
	})
}

func buildPythonFindings(auditID, root string, inv Inventory) []Finding {
	if _, ok := inv.Stack["python"]; !ok {
		return nil
	}
	var findings []Finding
	for _, rel := range inv.Files {
		if !strings.HasSuffix(rel, ".py") {
			continue
		}
		lines, ok := readLines(root, rel)
		if !ok {
			continue
		}
		for i, line := range lines {
			trimmed := strings.TrimSpace(line)
			if requestsCallRE.MatchString(trimmed) && !strings.Contains(trimmed, "timeout=") {
				findings = append(findings, newFinding(auditID, "python.requests_without_timeout", "Medium", "P2", "Probable", "python", "HTTP request without explicit timeout", "A requests call was detected without timeout= on the same call line.", "Media", rel, i+1, Evidence{Kind: "source", FilePath: rel, Line: i + 1, Summary: trimmed}, FindingDetails{
					WhyProblem:            "Network calls without timeouts can hang jobs or request handlers indefinitely.",
					Impact:                "Operational scripts or services may stall under network failure.",
					RiskOfChange:          "Low to medium; timeout choice can affect slow integrations.",
					MinimumRecommendation: "Add an explicit conservative timeout to the request call.",
					Avoid:                 "Do not add retries until timeout behavior is understood.",
					Validation:            "Run the script/tests with mocked slow network behavior if available.",
				}))
			}
			if strings.Contains(trimmed, "subprocess.") && strings.Contains(trimmed, "shell=True") {
				findings = append(findings, newFinding(auditID, "python.subprocess_shell_true", "High", "P1", "Confirmed", "python", "subprocess uses shell=True", "A subprocess call enables shell=True.", "Alta", rel, i+1, Evidence{Kind: "source", FilePath: rel, Line: i + 1, Summary: trimmed}, FindingDetails{
					WhyProblem:            "shell=True expands command parsing and can become command injection if input reaches it.",
					Impact:                "A crafted argument may execute unintended shell syntax.",
					RiskOfChange:          "Medium; command invocation semantics can change.",
					MinimumRecommendation: "Pass argv as a list and keep shell=False unless a shell feature is explicitly required.",
					Avoid:                 "Do not quote user input as the only mitigation.",
					Validation:            "Add a unit test around arguments containing spaces/shell metacharacters.",
				}))
			}
			if envIndexRE.MatchString(trimmed) {
				findings = append(findings, newFinding(auditID, "python.direct_environ_index", "Informative", "P3", "Hipótesis", "python", "Environment variable access may fail at import/runtime", "Direct os.environ[...] access raises KeyError when the variable is absent.", "Media", rel, i+1, Evidence{Kind: "source", FilePath: rel, Line: i + 1, Summary: trimmed}, FindingDetails{
					WhyProblem:            "Implicit required environment variables produce abrupt failures without validation context.",
					Impact:                "Jobs can fail at startup with unclear errors.",
					RiskOfChange:          "Low if replaced with explicit config validation.",
					MinimumRecommendation: "Centralize required env validation or use os.getenv with a clear error.",
					Avoid:                 "Do not silently default secrets or required URLs.",
					Validation:            "Run the entrypoint with the variable absent and verify the error is explicit.",
				}))
			}
			if isTopLevelSideEffect(lines, i, trimmed) {
				findings = append(findings, newFinding(auditID, "python.import_side_effect", "Low", "P3", "Hipótesis", "python", "Module import may perform external side effects", "A top-level external call was detected outside a __main__ guard.", "Baja", rel, i+1, Evidence{Kind: "source", FilePath: rel, Line: i + 1, Summary: trimmed}, FindingDetails{
					WhyProblem:            "Import side effects make scripts harder to test and can trigger IO during discovery.",
					Impact:                "Tests or tooling may call external systems merely by importing a module.",
					RiskOfChange:          "Medium; moving code behind an entrypoint can affect script behavior.",
					MinimumRecommendation: "Move external calls into a function invoked by the explicit entrypoint.",
					Avoid:                 "Do not change command-line behavior while isolating import-time effects.",
					Validation:            "Import the module in a unit test and verify no external call runs.",
				}))
			}
		}
	}
	return findings
}

func buildSQLFindings(auditID, root string, inv Inventory) []Finding {
	if len(inv.Migrations) == 0 {
		return nil
	}
	var findings []Finding
	knownIndexes := indexedColumns(root, inv.Migrations)
	for _, rel := range inv.Migrations {
		lines, ok := readLines(root, rel)
		if !ok {
			continue
		}
		content := strings.Join(lines, "\n")
		lower := strings.ToLower(content)
		for _, block := range createTableBlocks(lines) {
			blockText := strings.Join(block.lines, "\n")
			if !strings.Contains(strings.ToLower(blockText), "primary key") {
				findings = append(findings, newFinding(auditID, "sql.table_without_primary_key", "Medium", "P2", "Confirmed", "postgresql", "CREATE TABLE without primary key", "A CREATE TABLE statement did not include PRIMARY KEY in its statement block.", "Alta", rel, block.line, Evidence{Kind: "sql", FilePath: rel, Line: block.line, Summary: firstLine(blockText)}, FindingDetails{
					WhyProblem:            "Tables without primary keys make updates, references and deduplication harder to reason about.",
					Impact:                "Data integrity and operational maintenance can degrade as rows grow.",
					RiskOfChange:          "High on existing data; adding PKs may require data cleanup.",
					MinimumRecommendation: "Confirm whether the table is intentionally keyless before adding a primary key migration.",
					Avoid:                 "Do not add a primary key without checking existing duplicate/null data.",
					Validation:            "Run schema migration tests and inspect existing data cardinality before production.",
				}))
			}
			if !strings.Contains(strings.ToLower(blockText), "foreign key") {
				for _, match := range sqlIDColumnRE.FindAllStringSubmatch(blockText, -1) {
					col := strings.ToLower(match[1])
					if !strings.Contains(strings.ToLower(blockText), "references") {
						findings = append(findings, newFinding(auditID, "sql.id_column_without_fk", "Informative", "P3", "Probable", "postgresql", "ID-like column has no visible foreign key", "A *_id column was found in a CREATE TABLE block without REFERENCES/FOREIGN KEY in the same statement.", "Media", rel, block.line, Evidence{Kind: "sql", FilePath: rel, Line: block.line, Summary: col + " appears in a table definition without visible FK constraint."}, FindingDetails{
							WhyProblem:            "Foreign-key-looking columns without constraints can allow orphaned rows.",
							Impact:                "Data integrity may depend entirely on application code.",
							RiskOfChange:          "High on existing data; constraints may fail if orphan records already exist.",
							MinimumRecommendation: "Verify intended relationship and existing data before adding a FK.",
							Avoid:                 "Do not add FKs blindly on large tables without lock/data impact review.",
							Validation:            "Run orphan checks and migration tests before schema changes.",
						}))
						break
					}
				}
			}
		}
		for i, line := range lines {
			upper := strings.ToUpper(line)
			if strings.Contains(upper, "DROP TABLE") || (strings.Contains(upper, "ALTER TABLE") && strings.Contains(upper, " DROP")) {
				findings = append(findings, newFinding(auditID, "sql.destructive_migration_operation", "Medium", "P2", "Probable", "postgresql", "Migration contains potentially destructive schema operation", "A DROP TABLE or ALTER TABLE DROP operation was detected.", "Media", rel, i+1, Evidence{Kind: "sql", FilePath: rel, Line: i + 1, Summary: strings.TrimSpace(line)}, FindingDetails{
					WhyProblem:            "Destructive DDL can remove data or block production tables.",
					Impact:                "Deployments may cause data loss or extended locks if not planned.",
					RiskOfChange:          "Medium; mitigation usually requires migration strategy, not code cleanup.",
					MinimumRecommendation: "Require an explicit data/lock review before running the migration.",
					Avoid:                 "Do not rewrite migration history if it has already been applied.",
					Validation:            "Run migration tests against a copy with realistic data size.",
				}))
			}
		}
		for _, stmt := range sqlStatements(content) {
			up := strings.ToUpper(stmt.text)
			if (strings.Contains(up, " LIMIT ") || strings.Contains(up, " OFFSET ")) && !strings.Contains(up, " ORDER BY ") {
				findings = append(findings, newFinding(auditID, "sql.limit_without_order", "Informative", "P3", "Hipótesis", "postgresql", "LIMIT/OFFSET query has no ORDER BY", "A query uses LIMIT or OFFSET without an ORDER BY in the same statement.", "Media", rel, stmt.line, Evidence{Kind: "sql", FilePath: rel, Line: stmt.line, Summary: firstLine(stmt.text)}, FindingDetails{
					WhyProblem:            "Pagination without ordering can return unstable rows across executions.",
					Impact:                "Users or jobs may see duplicate/missing rows when data changes.",
					RiskOfChange:          "Medium; adding order can affect query plan and visible ordering.",
					MinimumRecommendation: "Add an ORDER BY that matches the intended stable ordering.",
					Avoid:                 "Do not add arbitrary ordering without product intent.",
					Validation:            "Run query tests and EXPLAIN for the chosen ordering/index.",
				}))
			}
			if match := whereColumnRE.FindStringSubmatch(stmt.text); len(match) == 2 {
				col := strings.ToLower(strings.TrimPrefix(match[1], "."))
				if !knownIndexes[col] && !strings.Contains(lower, "primary key") {
					findings = append(findings, newFinding(auditID, "sql.filter_without_visible_index", "Informative", "P3", "Hipótesis", "postgresql", "Filtered column has no visible index evidence", "A WHERE equality filter was found and no CREATE INDEX for the filtered column was visible in scanned SQL.", "Baja", rel, stmt.line, Evidence{Kind: "sql", FilePath: rel, Line: stmt.line, Summary: firstLine(stmt.text)}, FindingDetails{
						WhyProblem:            "Frequently filtered columns may need an index, but static analysis cannot prove frequency.",
						Impact:                "Potential performance risk on large tables.",
						RiskOfChange:          "Medium; indexes affect writes and storage.",
						MinimumRecommendation: "Only add an index after confirming query frequency and EXPLAIN evidence.",
						Avoid:                 "Do not add indexes based on this hypothesis alone.",
						Validation:            "Capture EXPLAIN ANALYZE on representative data before changing schema.",
					}))
				}
			}
		}
	}
	return findings
}

func buildTestResultFindings(auditID string, tests []TestResult) []Finding {
	var findings []Finding
	for _, t := range tests {
		if t.Status != "failed" && t.Status != "timeout" && t.Status != "blocked" {
			continue
		}
		severity := "Medium"
		priority := "P2"
		state := "Confirmed"
		if t.Status == "blocked" {
			severity = "Low"
			priority = "P3"
			state = "Probable"
		}
		findings = append(findings, newFinding(auditID, "tests.result_not_passing", severity, priority, state, "tests", "Audit test command did not pass: "+t.Name, "ToolLab recorded a test result with status "+t.Status+".", "Alta", t.GeneratedPath, 0, Evidence{Kind: "test", Command: t.Command, FilePath: t.GeneratedPath, Summary: fmt.Sprintf("%s status: %s", t.Name, t.Status)}, FindingDetails{
			WhyProblem:            "A failing or blocked validation command reduces confidence in repository health.",
			Impact:                "The current audit cannot establish that existing behavior is protected.",
			RiskOfChange:          "Low if the fix is limited to making the validation command runnable or correcting the failing behavior.",
			MinimumRecommendation: "Inspect the command output and fix the smallest cause of the failure/block.",
			Avoid:                 "Do not silence or remove the validation command to improve score.",
			Validation:            "Re-run the audit and confirm the same test result passes.",
		}))
	}
	return findings
}

func hasAnyFile(files []string, names ...string) bool {
	for _, f := range files {
		for _, name := range names {
			if f == name || strings.HasSuffix(f, "/"+name) {
				return true
			}
		}
	}
	return false
}

func readLines(root, rel string) ([]string, bool) {
	data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(rel)))
	if err != nil {
		return nil, false
	}
	return strings.Split(string(data), "\n"), true
}

func readPackageScripts(root string) (map[string]string, bool) {
	data, err := os.ReadFile(filepath.Join(root, "package.json"))
	if err != nil {
		return nil, false
	}
	var pkg struct {
		Scripts map[string]string `json:"scripts"`
	}
	if json.Unmarshal(data, &pkg) != nil || pkg.Scripts == nil {
		return nil, false
	}
	return pkg.Scripts, true
}

func suspiciousGoRoutineFile(rel string) bool {
	return strings.Contains(rel, "handler") || strings.Contains(rel, "service") || strings.Contains(rel, "usecase") || strings.Contains(rel, "worker")
}

func ignoredCriticalError(line string) bool {
	if !strings.Contains(line, "_ =") {
		return false
	}
	for _, needle := range []string{".Exec(", ".Query(", ".Save", "os.WriteFile", "os.ReadFile", ".Run(", ".CombinedOutput(", ".Decode("} {
		if strings.Contains(line, needle) {
			return true
		}
	}
	return false
}

func isJSLike(rel string) bool {
	lower := strings.ToLower(rel)
	return strings.HasSuffix(lower, ".ts") || strings.HasSuffix(lower, ".tsx") || strings.HasSuffix(lower, ".js") || strings.HasSuffix(lower, ".jsx")
}

func isCentralAPIFile(rel string) bool {
	return strings.Contains(rel, "lib/api") || strings.Contains(rel, "api/client") || strings.Contains(rel, "services/api")
}

func containsAPICall(line string) bool {
	return strings.Contains(line, "fetch(") || strings.Contains(line, "axios.") || strings.Contains(line, "axios(")
}

func effectWindowSuspicious(lines []string, start int) bool {
	window := strings.Join(windowLines(lines, start, 25), "\n")
	return containsAPICall(window) && (strings.Contains(window, "[]") || !strings.Contains(window, "],"))
}

func lineWindowContains(lines []string, start, size int, needle string) bool {
	return strings.Contains(strings.Join(windowLines(lines, start, size), "\n"), needle)
}

func windowLines(lines []string, start, size int) []string {
	if start < 0 {
		start = 0
	}
	end := start + size
	if end > len(lines) {
		end = len(lines)
	}
	return lines[start:end]
}

func isTopLevelSideEffect(lines []string, idx int, trimmed string) bool {
	if trimmed == "" || strings.HasPrefix(trimmed, "#") || strings.HasPrefix(trimmed, "def ") || strings.HasPrefix(trimmed, "class ") || strings.HasPrefix(trimmed, "import ") || strings.HasPrefix(trimmed, "from ") {
		return false
	}
	if strings.HasPrefix(lines[idx], " ") || strings.HasPrefix(lines[idx], "\t") {
		return false
	}
	for _, prev := range lines[:idx] {
		if strings.Contains(prev, `if __name__ == "__main__"`) || strings.Contains(prev, "if __name__ == '__main__'") {
			return false
		}
	}
	return requestsCallRE.MatchString(trimmed) || strings.Contains(trimmed, "subprocess.") || strings.Contains(trimmed, "psycopg.connect") || strings.Contains(trimmed, "create_engine(")
}

type tableBlock struct {
	line  int
	lines []string
}

func createTableBlocks(lines []string) []tableBlock {
	var blocks []tableBlock
	for i := 0; i < len(lines); i++ {
		if !strings.Contains(strings.ToUpper(lines[i]), "CREATE TABLE") {
			continue
		}
		block := tableBlock{line: i + 1}
		for j := i; j < len(lines); j++ {
			block.lines = append(block.lines, lines[j])
			if strings.Contains(lines[j], ";") {
				i = j
				break
			}
		}
		blocks = append(blocks, block)
	}
	return blocks
}

type sqlStatement struct {
	line int
	text string
}

func sqlStatements(content string) []sqlStatement {
	var out []sqlStatement
	line := 1
	startLine := 1
	var b strings.Builder
	for _, r := range content {
		b.WriteRune(r)
		if r == '\n' {
			line++
		}
		if r == ';' {
			out = append(out, sqlStatement{line: startLine, text: b.String()})
			b.Reset()
			startLine = line
		}
	}
	if strings.TrimSpace(b.String()) != "" {
		out = append(out, sqlStatement{line: startLine, text: b.String()})
	}
	return out
}

func indexedColumns(root string, migrations []string) map[string]bool {
	indexes := map[string]bool{}
	re := regexp.MustCompile(`(?i)CREATE\s+INDEX.*\(([^)]+)\)`)
	for _, rel := range migrations {
		lines, ok := readLines(root, rel)
		if !ok {
			continue
		}
		for _, line := range lines {
			match := re.FindStringSubmatch(line)
			if len(match) != 2 {
				continue
			}
			for _, col := range strings.Split(match[1], ",") {
				indexes[strings.ToLower(strings.TrimSpace(col))] = true
			}
		}
	}
	return indexes
}

func firstLine(s string) string {
	for _, line := range strings.Split(s, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed != "" {
			return truncate(trimmed, 180)
		}
	}
	return ""
}
